// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQWoFhlgj8fb_ctZcR_Uh1eEDerbPqavc',
    appId: '1:587521057124:web:937da3362947e750ac5a71',
    messagingSenderId: '587521057124',
    projectId: 'ev-connect-app--2',
    authDomain: 'ev-connect-app--2.firebaseapp.com',
    storageBucket: 'ev-connect-app--2.appspot.com',
    measurementId: 'G-3QBGKCX9HN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzkpN0mY0VoWmG62Huk7JmJ0JxWCwBy0k',
    appId: '1:587521057124:android:613eeec7cdb3cd84ac5a71',
    messagingSenderId: '587521057124',
    projectId: 'ev-connect-app--2',
    storageBucket: 'ev-connect-app--2.appspot.com',
  );
}
